patches/0001-drm-msm-a6xx-Increase-GMU-FW-init-timeout.patch
patches/0002-power-supply-Add-driver-for-Qualcomm-PMIC-fuel-gauge.patch
patches/0003-ASoC-qdsp6-Add-shared-session-management-for-q6voice.patch
patches/0004-ASoC-qdsp6-Add-driver-for-Q6-Multimode-Voice-Manager.patch
patches/0005-ASoC-qdsp6-Add-driver-for-Q6-Core-Voice-Processor-q6.patch
patches/0006-ASoC-qdsp6-Add-driver-for-Q6-Core-Voice-Stream-q6cvs.patch
patches/0007-ASoC-qdsp6-Add-voice-call-functionality-in-Q6-Voice-.patch
patches/0008-ASoC-qdsp6-Add-Q6-Voice-DAI-driver-v2.patch
patches/0009-ASoC-qdsp6-q6voice-dai-Add-controls-for-voice-rx-and.patch
patches/0010-ASoC-qdsp6-q6voice-Add-getter-setter-for-rx-and-tx-p.patch
patches/0011-ASoC-qdsp6-q6voice-dai-Add-controls-for-SLIMBUS0-TX-.patch
patches/0012-ASoC-qdsp6-q6voice-dai-Introduce-VoiceMMode1-dai.patch
patches/0013-ASoC-qcom-qdsp6-q6voice-dai-implement-all-slimbus-tx.patch
patches/0014-arm64-dts-qcom-sdm845-Add-q6voice-APR-service-device.patch
patches/0015-media-i2c-Add-imx363-image-sensor-driver.patch
patches/0016-Input-touchscreen-stm-fts.patch
patches/0017-usb-typec-qcom-pmic-dispatch-port-backend-via-resour.patch
patches/0018-usb-typec-qcom-pmic-add-PMI8998-port-handler.patch
patches/0019-arm64-dts-qcom-pmi8998-add-Type-C-and-VBUS-regulator.patch
patches/0020-arm64-dts-qcom-sdm845-add-refgen-regulator-and-use-i.patch
patches/0021-Input-touchscreen-stm-ftm5-throttle-zero-pressure-wa.patch
patches/0022-Input-touchscreen-stm-ftm5-request-IRQ-with-NO_AUTOE.patch
patches/0023-Input-touchscreen-stm-ftm5-allow-board-to-narrow-act.patch
patches/0024-dt-bindings-display-panel-Add-Samsung-EA8074.patch
patches/0025-drm-panel-samsung-Add-driver-for-Samsung-EA8074.patch
patches/0026-media-i2c-imx363-start-MCLK-before-supplies.patch
patches/0027-ASoC-codecs-add-TAS2557-smart-amplifier-driver.patch
patches/0028-arm64-dts-qcom-add-Xiaomi-Mi-8-dipper.patch
patches/0029-arm64-dts-qcom-xiaomi-dipper-use-extracted-GPU-and-V.patch
patches/0030-BACKPORT-arm64-qcom-port-Xiaomi-Dipper-drivers-to-6..patch
patches/0031-media-venus-size-SDM845-v2-encoder-buffers.patch
patches/0032-media-venus-use-DMA-buffer-for-SDM845-v2-encoder-EOS.patch
patches/0033-arm64-dts-qcom-xiaomi-dipper-drop-unverified-ramoops.patch
patches/0034-arm64-dts-qcom-sdm845-Reserve-low-IOVA-range-for-Venus.patch
patches/0035-arm64-dts-qcom-xiaomi-dipper-reserve-Mi-8-firmware-gaps.patch
patches/0036-arm64-dts-qcom-xiaomi-dipper-restore-validated-ramoops.patch
